"""fix datetime types

Revision ID: 40816b9b4170
Revises: 8227c56fd9ab
Create Date: 2025-12-27 17:35:50.670434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40816b9b4170'
down_revision = '8227c56fd9ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
