"""add AI draft fields and PromptConfig

Revision ID: 6562749f3fc5
Revises: 40816b9b4170
Create Date: 2026-01-12 19:42:32.290883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6562749f3fc5'
down_revision = '40816b9b4170'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('sources')
    op.drop_table('analytics')
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('is_breaking', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('news_id', sa.INTEGER(), nullable=False),
    sa.Column('views', sa.INTEGER(), nullable=False),
    sa.Column('reactions', sa.INTEGER(), nullable=False),
    sa.Column('comments', sa.INTEGER(), nullable=False),
    sa.Column('reposts', sa.INTEGER(), nullable=False),
    sa.Column('click_rate', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('last_parsed', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('news_id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_message_id', sa.INTEGER(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
